[server]
port = 7860
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
showSidebarNavigation = false

[theme]
primaryColor = "#EC1776"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F6F9"
textColor = "#1C1C1C"
font = "sans serif"